/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Clients {
  address: string | null;
  archivedAt: string | null;
  clientType: Generated<string>;
  country: string;
  createdAt: Generated<string>;
  defaultCurrency: string | null;
  defaultOfferValidityDays: number | null;
  defaultPaymentTermsDays: number | null;
  email: string | null;
  emailBodyTemplate: string | null;
  emailFromAddress: string | null;
  emailFromName: string | null;
  emailSubjectTemplate: string | null;
  id: Generated<number | null>;
  name: string;
  oib: string | null;
  updatedAt: Generated<string>;
  vatNumber: string | null;
}

export interface ClientTaxIds {
  clientId: number;
  id: Generated<number | null>;
  label: string;
  value: string;
}

export interface CompanyProfile {
  address: string;
  createdAt: Generated<string>;
  defaultPaymentTermsDays: Generated<number>;
  emailBodyTemplate: string | null;
  emailFromAddress: string;
  emailFromName: string;
  emailSubjectTemplate: string | null;
  iban: string;
  id: Generated<number | null>;
  issuerName: string;
  legalTextServiceDomesticHr: string | null;
  legalTextServiceEuB2bReverseChargeEn: string | null;
  legalTextServiceEuB2bReverseChargeHr: string | null;
  legalTextServiceEuB2bWithoutVatIdEn: string | null;
  legalTextServiceEuB2bWithoutVatIdHr: string | null;
  legalTextServiceEuB2cEn: string | null;
  legalTextServiceEuB2cHr: string | null;
  legalTextServiceNonEuB2bEn: string | null;
  legalTextServiceNonEuB2bHr: string | null;
  legalTextServiceNonEuB2cEn: string | null;
  legalTextServiceNonEuB2cHr: string | null;
  logoPath: string | null;
  name: string;
  oib: string;
  phone: string;
  swift: string;
  taglineEn: string | null;
  taglineHr: string | null;
  updatedAt: Generated<string>;
}

export interface DocumentNumberSequences {
  id: Generated<number | null>;
  lastValue: number;
  paymentMethodId: number;
  year: number;
}

export interface EmailLogs {
  body: string;
  createdAt: Generated<string>;
  errorMessage: string | null;
  id: Generated<number | null>;
  invoiceId: number;
  postmarkMessageId: string | null;
  postmarkResponse: string | null;
  recipient: string;
  senderEmail: string;
  senderName: string;
  status: string;
  subject: string;
}

export interface HolidaysCache {
  date: string;
  fetchedAt: Generated<string>;
  id: Generated<number | null>;
  name: string;
  year: number;
}

export interface Invoices {
  clientId: number | null;
  createdAt: Generated<string>;
  currency: string | null;
  deliveryDate: string | null;
  documentNumber: string | null;
  dueDate: string | null;
  email: string | null;
  exchangeRateDate: string | null;
  exchangeRateText: string | null;
  id: Generated<number | null>;
  issueDate: string | null;
  locationId: number | null;
  notesEn: string | null;
  notesHr: string | null;
  originalInvoiceNumber: string | null;
  paymentDate: string | null;
  paymentMethodId: number | null;
  pdfHashEn: string | null;
  pdfHashHr: string | null;
  pdfPathEn: string | null;
  pdfPathHr: string | null;
  status: Generated<string>;
  type: Generated<string>;
  updatedAt: Generated<string>;
}

export interface LineItems {
  descriptionEn: string | null;
  descriptionHr: string | null;
  id: Generated<number | null>;
  invoiceId: number;
  position: number;
  quantity: number | null;
  unitPrice: number | null;
}

export interface Locations {
  createdAt: Generated<string>;
  id: Generated<number | null>;
  isDefault: Generated<number>;
  nameEn: string | null;
  nameHr: string;
  number: number;
  updatedAt: Generated<string>;
}

export interface OfferNumberSequences {
  id: Generated<number | null>;
  lastValue: number;
  year: number;
}

export interface PaymentMethods {
  createdAt: Generated<string>;
  id: Generated<number | null>;
  isDefault: Generated<number>;
  nameEn: string | null;
  nameHr: string;
  number: number;
  updatedAt: Generated<string>;
}

export interface ServiceCatalog {
  createdAt: Generated<string>;
  descriptionEn: string | null;
  descriptionHr: string;
  id: Generated<number | null>;
  updatedAt: Generated<string>;
}

export interface Settings {
  defaultOfferValidityDays: Generated<number>;
  defaultPaymentTermsDays: Generated<number>;
  defaultVatRate: Generated<number>;
  id: Generated<number | null>;
  postmarkApiKey: string | null;
  supportedCurrencies: Generated<string>;
  updatedAt: Generated<string>;
}

export interface ViesVerifications {
  address: string | null;
  countryCode: string;
  createdAt: Generated<string>;
  id: Generated<number | null>;
  invoiceId: number;
  name: string | null;
  rawResponse: string;
  requestDate: string | null;
  valid: number;
  vatNumber: string;
}

export interface DB {
  clients: Clients;
  clientTaxIds: ClientTaxIds;
  companyProfile: CompanyProfile;
  documentNumberSequences: DocumentNumberSequences;
  emailLogs: EmailLogs;
  holidaysCache: HolidaysCache;
  invoices: Invoices;
  lineItems: LineItems;
  locations: Locations;
  offerNumberSequences: OfferNumberSequences;
  paymentMethods: PaymentMethods;
  serviceCatalog: ServiceCatalog;
  settings: Settings;
  viesVerifications: ViesVerifications;
}
