/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Companies {
  address: string;
  createdAt: Generated<string>;
  defaultPaymentTermsDays: Generated<number>;
  emailBodyTemplate: string | null;
  emailFromAddress: string;
  emailFromName: string;
  emailSubjectTemplate: string | null;
  iban: string;
  id: Generated<number | null>;
  issuerName: string;
  legalTextDomestic: string | null;
  legalTextForeignEn: string | null;
  legalTextForeignHr: string | null;
  logoPath: string | null;
  name: string;
  oib: string;
  phone: string;
  swift: string;
  taglineEn: string | null;
  taglineHr: string | null;
  updatedAt: Generated<string>;
}

export interface Locations {
  companyId: number;
  createdAt: Generated<string>;
  id: Generated<number | null>;
  isDefault: Generated<number>;
  nameEn: string | null;
  nameHr: string;
  number: number;
  updatedAt: Generated<string>;
}

export interface PaymentMethods {
  companyId: number;
  createdAt: Generated<string>;
  id: Generated<number | null>;
  isDefault: Generated<number>;
  nameEn: string | null;
  nameHr: string;
  number: number;
  updatedAt: Generated<string>;
}

export interface DB {
  companies: Companies;
  locations: Locations;
  paymentMethods: PaymentMethods;
}
