strictDepBuilds: false

supportedArchitectures:
  os:
    - darwin
    - linux
  cpu:
    - arm64
    - x64

storeDir: ../.pnpm-store
packageImportMethod: hardlink

allowBuilds:
  better-sqlite3: true
  esbuild: false
  msw: false
  sharp: false

minimumReleaseAgeExclude:
  - playwright-core@1.61.0
  - playwright@1.61.0
